In [83]:
from pandas import Series, DataFrame
import scipy.io as sio  
import pandas as pd
import numpy as np
import sys
import requests
import json

In [120]:
df = pd.read_csv('node.csv',header=None)
df

0    1    2
0     D1  121    8
1     D2  193  137
2    Z01  205   92
3    Z02  159   62
4    Z03  143   38
5    Z04  108   80
6    Z05   55   38
7    Z06   62  105
8    F01  135  142
9    F02  127  143
10   F03  124  129
11   F04  115  130
12   F05  105  130
13   F06  108  145
14   F07   90  145
15   F08   72  142
16   F09   60  139
17   F10   70  121
18   F11  100  121
19   F12   53  132
20   F13   37  127
21   F14   25  120
22   F15   15  115
23   F16    7  105
24   F17   28  106
25   F18   24   90
26   F19   45   90
27   F20   49   82
28   F21   16   76
29   F22   15   70
..   ...  ...  ...
100  J33  175  115
101  J34  155  105
102  J35  140  105
103  J36  137   87
104  J37  106   94
105  J38  102   72
106  J39   77   79
107  J40   83   65
108  J41   58   47
109  J42   93   45
110  J43   33   29
111  J44   58   24
112  J45   80   30
113  J46   80   13
114  J47  234  118
115  J48  220  110
116  J49  168   83
117  J50  193   78
118  J51  149   68
119  J52  143   55
120  J53  195   60
121  J54  164   50
122  J55  183   50
123  J56  221   54
124  J57  165   40
125  J58  178   33
126  J59  196   39
127  J60  226   43
128  J61  160   18
129  J62  214   23

[130 rows x 3 columns]

In [5]:
dict=[[1,2,3,4,5,6],[2,3,4,5,6,7],[3,4,5,6,7,8],[4,5,6,7,8,9],[5,6,7,8,9,10]]
data=pd.DataFrame(dict)
a=[]
for indexs in data.index:
    a.append(data.loc[indexs].values[0:-1])
a

[array([1, 2, 3, 4, 5], dtype=int64),
 array([2, 3, 4, 5, 6], dtype=int64),
 array([3, 4, 5, 6, 7], dtype=int64),
 array([4, 5, 6, 7, 8], dtype=int64),
 array([5, 6, 7, 8, 9], dtype=int64)]

In [102]:
dis=[]
for indexs in df.index:
    dis.append(df.loc[indexs].values[1:])
dis=np.array(dis)

In [103]:
dis.shape

(130, 2)

In [178]:
df.ix[78],df.ix[98]

(0    J11
 1     99
 2      3
 Name: 78, dtype: object, 0    J31
 1     23
 2     57
 Name: 98, dtype: object)

In [20]:
dis[0][0],dis[0][1:]

('D1', array([121, 8], dtype=object))

In [22]:
ed = pd.read_csv('edge.csv',header=None)
ed

0    1
0    F16  J27
1    F15  J27
2    F14  J27
3    F17  J27
4    J26  J27
5    J28  J27
6    F13  J26
7    F12  J26
8    Z06  J26
9    J24  J26
10   J28  Z06
11   J25  Z06
12   J16  Z06
13   F18  J28
14   F19  J28
15   J30  J28
16   J29  J28
17   F21  J30
18   F22  J30
19   J29  J30
20   J31  J30
21   F20  J29
22   J31  J29
23   J18  J29
24   F23  J31
25   J20  J31
26   J19  J31
27   J19  J20
28   J18  J19
29   J43  J19
..   ...  ...
144  Z01  J48
145  J12  J13
146  J14  J13
147  J32  J13
148  J32  J12
149  J35  J14
150  F24  J32
151  J33  J32
152  F25  J33
153  J04  Z01
154  J50  Z01
155  F50  J50
156  J04  J50
157  J49  J50
158  F48  J49
159  F49  J49
160  J05  J49
161  J06  J05
162  J04  J05
163  J33  J04
164  J34  J33
165  F26  J34
166  J35  J34
167  J05  J34
168  J36  J34
169  F27  J35
170  F28  J35
171  F29  J36
172  F30  J36
173  J06  J36

[174 rows x 2 columns]

In [23]:
edge=[]
for indexs in ed.index:
    edge.append(ed.loc[indexs].values[:])
edge=np.array(edge)

In [24]:
edge.shape

(174, 2)

In [27]:
dis.shape,edge.shape

((130, 3), (174, 2))

In [42]:
[dis[0][0],dis[1][0]] in edge

True

In [76]:
edges={}
for row in edge:
    if row[0] not in edges.keys():
        edges[row[0]]=set()
    edges[row[0]].add(row[1])
for row in edge:
    if row[1] not in edges.keys():
        edges[row[1]]=set()
    edges[row[1]].add(row[0])

In [81]:
W=np.zeros((130,130))
for i in range(130):
    start=dis[i]
    for j in range(130):
        ends=dis[j]
        if  ends[0] not in edges[start[0]]:
            W[i][j]= 0
        else:
            W[i][j]= int(np.sqrt(np.square(start[1]+ends[1])+np.square(start[2]+ends[2])))

In [82]:
W

array([[   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       ..., 
       [   0.,    0.,    0., ...,    0.,    0.,  444.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,  444.,    0.,    0.]])

In [84]:
sio.savemat('ddd.mat', {'ddd': W})  

In [172]:
sio.savemat('jiedian.mat', {'jiedian': disss})  

In [108]:
np.save('jiedian',dis)

In [166]:
np.savetxt(r'C:\Users\Administrator\Desktop\ELM半监督密度聚类\jiedian.txt',dis)

In [138]:
f = open("jiedian.txt",'wb')
f.write(dis)
f.close()

In [152]:
dis_li=dis.tolist()
dis_li

[[121, 8],
 [193, 137],
 [205, 92],
 [159, 62],
 [143, 38],
 [108, 80],
 [55, 38],
 [62, 105],
 [135, 142],
 [127, 143],
 [124, 129],
 [115, 130],
 [105, 130],
 [108, 145],
 [90, 145],
 [72, 142],
 [60, 139],
 [70, 121],
 [100, 121],
 [53, 132],
 [37, 127],
 [25, 120],
 [15, 115],
 [7, 105],
 [28, 106],
 [24, 90],
 [45, 90],
 [49, 82],
 [16, 76],
 [15, 70],
 [14, 56],
 [168, 126],
 [165, 117],
 [165, 105],
 [145, 113],
 [132, 100],
 [130, 94],
 [130, 80],
 [110, 100],
 [114, 90],
 [95, 90],
 [95, 77],
 [106, 63],
 [86, 75],
 [72, 70],
 [74, 60],
 [79, 53],
 [68, 46],
 [46, 20],
 [59, 15],
 [77, 5],
 [240, 127],
 [240, 107],
 [230, 100],
 [220, 98],
 [158, 77],
 [176, 75],
 [206, 77],
 [184, 62],
 [215, 62],
 [227, 64],
 [206, 46],
 [231, 49],
 [232, 37],
 [148, 15],
 [170, 17],
 [201, 22],
 [224, 20],
 [237, 137],
 [232, 127],
 [204, 119],
 [188, 100],
 [168, 94],
 [143, 74],
 [117, 67],
 [122, 48],
 [108, 38],
 [102, 23],
 [99, 3],
 [170, 145],
 [150, 133],
 [140, 120],
 [105, 108],
 

In [163]:
disss =[[float(item[0]),float(item[1]),item[-1]] for item in dis_li]


[[121.0, 8.0, 0],
 [193.0, 137.0, 0],
 [205.0, 92.0, 0],
 [159.0, 62.0, 0],
 [143.0, 38.0, 0],
 [108.0, 80.0, 0],
 [55.0, 38.0, 0],
 [62.0, 105.0, 0],
 [135.0, 142.0, 0],
 [127.0, 143.0, 0],
 [124.0, 129.0, 0],
 [115.0, 130.0, 0],
 [105.0, 130.0, 0],
 [108.0, 145.0, 0],
 [90.0, 145.0, 0],
 [72.0, 142.0, 0],
 [60.0, 139.0, 0],
 [70.0, 121.0, 0],
 [100.0, 121.0, 0],
 [53.0, 132.0, 0],
 [37.0, 127.0, 0],
 [25.0, 120.0, 0],
 [15.0, 115.0, 0],
 [7.0, 105.0, 0],
 [28.0, 106.0, 0],
 [24.0, 90.0, 0],
 [45.0, 90.0, 0],
 [49.0, 82.0, 0],
 [16.0, 76.0, 0],
 [15.0, 70.0, 0],
 [14.0, 56.0, 0],
 [168.0, 126.0, 0],
 [165.0, 117.0, 0],
 [165.0, 105.0, 0],
 [145.0, 113.0, 0],
 [132.0, 100.0, 0],
 [130.0, 94.0, 0],
 [130.0, 80.0, 0],
 [110.0, 100.0, 0],
 [114.0, 90.0, 0],
 [95.0, 90.0, 0],
 [95.0, 77.0, 0],
 [106.0, 63.0, 0],
 [86.0, 75.0, 0],
 [72.0, 70.0, 0],
 [74.0, 60.0, 0],
 [79.0, 53.0, 0],
 [68.0, 46.0, 0],
 [46.0, 20.0, 0],
 [59.0, 15.0, 0],
 [77.0, 5.0, 0],
 [240.0, 127.0, 0],
 [240.0, 107.0, 0

In [171]:
disss

[[121.0, 8.0, 0],
 [193.0, 137.0, 0],
 [205.0, 92.0, 0],
 [159.0, 62.0, 0],
 [143.0, 38.0, 0],
 [108.0, 80.0, 0],
 [55.0, 38.0, 0],
 [62.0, 105.0, 0],
 [135.0, 142.0, 0],
 [127.0, 143.0, 0],
 [124.0, 129.0, 0],
 [115.0, 130.0, 0],
 [105.0, 130.0, 0],
 [108.0, 145.0, 0],
 [90.0, 145.0, 0],
 [72.0, 142.0, 0],
 [60.0, 139.0, 0],
 [70.0, 121.0, 0],
 [100.0, 121.0, 0],
 [53.0, 132.0, 0],
 [37.0, 127.0, 0],
 [25.0, 120.0, 0],
 [15.0, 115.0, 0],
 [7.0, 105.0, 0],
 [28.0, 106.0, 0],
 [24.0, 90.0, 0],
 [45.0, 90.0, 0],
 [49.0, 82.0, 0],
 [16.0, 76.0, 0],
 [15.0, 70.0, 0],
 [14.0, 56.0, 0],
 [168.0, 126.0, 0],
 [165.0, 117.0, 0],
 [165.0, 105.0, 0],
 [145.0, 113.0, 0],
 [132.0, 100.0, 0],
 [130.0, 94.0, 0],
 [130.0, 80.0, 0],
 [110.0, 100.0, 0],
 [114.0, 90.0, 0],
 [95.0, 90.0, 0],
 [95.0, 77.0, 0],
 [106.0, 63.0, 0],
 [86.0, 75.0, 0],
 [72.0, 70.0, 0],
 [74.0, 60.0, 0],
 [79.0, 53.0, 0],
 [68.0, 46.0, 0],
 [46.0, 20.0, 0],
 [59.0, 15.0, 0],
 [77.0, 5.0, 0],
 [240.0, 127.0, 0],
 [240.0, 107.0, 0